[package]
name = "teleps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.9"

[[bin]]
name = "pub"
path = "src/bin/publisher.rs"

[[bin]]
name = "sub"
path = "src/bin/subscriber.rs"
